version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 300
      runas: root

#ec2 setup #https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install-ubuntu.html
# apt-get update
# apt-get install ruby2.0
# apt-get install wget
# cd /home/ubunutu
# wget https://aws-codedeploy-us-east-2.s3.amazonaws.com/latest/install
# chmod +x ./install
# sudo ./install auto
